project:
  type: website

website:
  title: "JKF Wadokai Netherlands: Karate Seminar 2025"
  navbar:
    background: "#145DA0"
    search: true
    right:
      - href: index.qmd
        text: Home
      - program.qmd
      - registration.qmd
      - getting-around.qmd
      - contact.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



